### ISSUE TITLE
Monochrome 1.3" 128x64 OLED graphic display incorect part

### ISSUE THREAD

**Issue by MatejGomboc** [Safecast/bGeigieNanoKit#38]
There should be monochrome 1.3" 128x64 OLED graphic display instead Monochrome 1.3" 128x32 OLED graphic display in the parts list.

**Comment by nokton** [comment]
Actually the bGeigie is designed to take both 32 and 64 line OLED displays. The 32 line is a physical smaller display. The logic for this is that in case the 64 line would be out of stock, the 32 line can be used in stead.
