### ISSUE TITLE
Wrong overlay text on the PCB ?

### ISSUE THREAD

**Issue by oz1cxp** [Safecast/bGeigieNanoKit#46]
Hi

I just bought a kit from kithub, and have soldered the passive component on the pcb, and then i find a problem.
I have been working in electronics for 40+ years, so i know colorcodes by heart, and just placed the resistors according to the text on the PCB, but then when i compared to the picture in the wiki of a PCB with resistors, R8 and R9 are swapped. I have placed them correct according to the text on the PCB, but not according to the placement guide in the wiki, so am I right in thinking that the text is wrong on the PCB ?

**Comment by jamoross** [comment]
oz1cxp -

The text is not wrong on the PCB. The positions of R8 and R9 got swapped some time ago.  The image you saw was likely of a unit with a mainboard version V1.0r2, I'm guessing you have the most recent board (V1.1r5) with R8 to the right of R9 (farther from the buzzer).

**Comment by oz1cxp** [comment]
thank you, yes it seems like  have a newer PCB than shown in the assembly wiki. I finished the build and it works fine.
