### ISSUE TITLE
bBeigie Nano Mac Uploader 1.4.1 Issue

### ISSUE THREAD

**Issue by diehl** [Safecast/bGeigieNanoKit#48]
Hello, 

When I run the latest uploader, I'm seeing the following in the details. Any suggestions?
```
TERM environment variable not set.
Safecast

Firmware Uploader Mac

The following is a list of the available serial ports:

No relevant port
```

**Comment by diehl** [comment]
Well I realized one issue. I shouldn't be plugging it into the computer with the power switch set to the on position. Now I'm seeing the following:
```
TERM environment variable not set.
Safecast

Firmware Uploader Mac

The following is a list of the available serial ports:

1. /dev/tty.usbserial-FT9QCYW2

One relevant port so selecting it automatically : /dev/tty.usbserial-FT9QCYW2
1. bGeigieNano.hex
TERM environment variable not set.
Safecast firmware Updater

Writing - bGeigieNano.hex
to port - /dev/tty.usbserial-FT9QCYW2
IC      - atmega328p

avrdude: stk500_recv(): programmer is not responding

avrdude done.  Thank you.
```

**Comment by robouden** [comment]
Chris,

Did you remove the BLE Xbee?

regards
rob



Regards,
Rob Oudendijk Yuka Hayashi
http://yr-design.biz   http://oudendijk.biz  http://about.me/robouden
tel +81 80-22605966  Skype: robouden  Facebook:robouden
<http://on.fb.me/QeKw2P> linkedin:robouden
<https://www.linkedin.com/in/roboudendijk>

**Comment by diehl** [comment]
Thanks Rob. That's exactly the step I was missing. 

Best regards, 

Chris
