### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by cw1812** [Safecast/bGeigieNanoKit#56]
Cannot compile with arduino software. Here is the error:

Sketch uses 33942 bytes (110%) of program storage space. Maximum is 30720 bytes.text section exceeds available space in board

Global variables use 1317 bytes (64%) of dynamic memory, leaving 731 bytes for local variables. Maximum is 2048 bytes.
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
Error compiling for board Arduino Fio.

**Comment by robouden** [comment]
Correct. Can not do that. You need to use the make file. Or use the branch I made for ACSII use only that is 11k smaller.[https://github.com/Safecast/bGeigieNanoKit/tree/ASCII_new]( https://github.com/Safecast/bGeigieNanoKit/tree/ASCII_new)

Or follow the guide in the read me.:

```
export ARDUINODIR=/home/geigie/arduino-1.0.1/
export SERIALDEV=/dev/ttyUSB0
export BOARD=fio
cp -r libraries /home/geigie/arduino-1.0.1/
make
make upload
```

**Comment by cw1812** [comment]
Hi robouden,

The ASCII_new work for me.

Thanks for your effort!

**Comment by robouden** [comment]
But the display is not "standard" if you flash the file to the bGeigieNano.

**Comment by robouden** [comment]
The ASCII new version is a work in progress to ad shock sensor for bGeigeiCast dimming of the display.
