### ISSUE TITLE
bGeigie Nano 1.4.3 not locking GPS

### ISSUE THREAD

**Issue by pawelngei** [Safecast/bGeigieNanoKit#59]
I just bought and assembled a bGeigie Nano kit following [the assembly manual](https://github.com/Safecast/bGeigieNanoKit/wiki/Assembly-Manual) and flashed it with 1.4.3 firmware (last version from 8 days ago). I ran the [power on test](https://github.com/Safecast/bGeigieNanoKit/wiki/Assembly-Manual#power-on-test) successfully. 

After installing the tube and inserting the SD card I can't get the GPS to lock to any satellite. I left the bGeigie outside for 20 minutes - nothing, in any of the modes. Tried resetting the GPS a few times (by removing the SD card), to no avail. Copied the SD configs from [this repo](https://github.com/Safecast/bGeigieNanoKit/tree/master/SD%20card), no change.

The red FIX LED on the GPS module keeps blinking. All the other functions seem to work properly.

What is the proper way to debug it? Is it possible to re-flash the GPS firmware?

**Comment by jamoross** [comment]
Hello -

If the red LED on the GPS unit is blinking slowly (1sec on, 1sec off) then
it is in acquisition mode and should eventually get a location fix.  The
parameter settings the bGeigie sends it after a reset control how it
communicates and saves its place for a “warm start”.  After reset, or just
not being turned on for many days, it must do a “cold start” and needs a
wide clear view of the sky.

It’s possible an external antenna would help it get an initial fix, but
that’s not necessary.   I would put it outside in a wide open space, on a
roof if in a city, and let it sit. The bGeigie should not be in log mode
(put the mode switch up).

It’s also possible you have a defective GPS module but it would be the
first.  I’ve seen bad displays, FIOs, and plenty of bad logger modules, but
not a GPS.  Always a first time I guess…

If there is a Bluetooth module, remove it until the GPS gets a first fix.
Also make sure there are no SD card errors as that can cause the main
processor to repeatedly reset the GPS controller.

Let me know how it goes.

- jam

**Comment by pawelngei** [comment]
Thanks a lot @jamoross !

Once I set it to the Surface Mode (up), the GPS no longer blinks every few seconds, but the LOG red LED on the motherboard does. A short video:

https://user-images.githubusercontent.com/4021653/127784926-784e3614-7b9a-4353-9815-8467882aede6.mp4

Is this normal for the device?

**Comment by jamoross** [comment]
No, that is definitely not normal.  It looks like the FIO is constantly
resetting itself. I’d check all your connections looking for “cold” solder
joints and inadvertent bridges.

I’m also worried that the component leads weren’t trimmed short enough on
the back of the main board and something is shorting out.

- jam

**Comment by pawelngei** [comment]
Thank you @jamoross !

How can I know FIO is resetting? Is the red light indicating a restart? Blinking of the other components?

I cut all the components leads, re-soldered one resistor and it's not blinking as often. I'll keep it on today and see if it'll find a satellite.

In the Surface mode, is the second line supposed to be blinking constantly?

Short vids of my today's down mode:

https://user-images.githubusercontent.com/4021653/127841227-9306ece1-f0d8-4965-9098-6e87d5232f93.mp4

And up mode:

https://user-images.githubusercontent.com/4021653/127841278-253fa072-2b34-420e-837f-3f27203ba581.mp4

**Comment by pawelngei** [comment]
(the screen flickering above is caused by the camera, the screen looks okay to the human eye).

Another interesting thing I noticed: In LOG mode, each "minute" is counted each 2-3 seconds, so after 3 hours it's showing about 60h.

**Comment by pawelngei** [comment]
Looking at https://youtu.be/AgJoYGkN70E?t=50 , in the Surface mode the second line on the display changes every few seconds, while in my hardware it keeps flickering. Is the hardware clock broken? Is it a firmware issue? 

https://user-images.githubusercontent.com/4021653/127909667-84c2b563-3e47-4c72-a2b2-dffdce0376ae.mp4

**Comment by robouden** [comment]
Seeing the flicking, and the time issues with logging I am wondering what firmware did you use? Did you compile by yourself the code from a few days ago? 

Regards,
Rob

**Comment by pawelngei** [comment]
Thanks @robouden ! I used the .hex available in Github from this commit: https://github.com/Safecast/bGeigieNanoKit/commit/69b7a3aa9df2c30b8ecb55c01f806e7af7c3ccef#diff-4e0b6454608d1370aa77d4b3332749e60647441c08577cb494dc49149d7c4053

Should I compile it myself, or try the new .hex from yesterday?

**Comment by pawelngei** [comment]
Update: it looks like flashing the new firmware 1.4.4 fixed the issue. The screen no longer flickers and the GPS works correctly. The only issue is that switching between modes takes a few seconds.

**Comment by robouden** [comment]
Happy V1.4.4 works. You seem to be the first one to use it.
Switching mode is delay is "normal". Due to the 5 seconds updates on the main code.

Regards,
Rob

**Comment by robouden** [comment]
> Update: it looks like flashing the new firmware 1.4.4 fixed the issue. The screen no longer flickers and the GPS works correctly. The only issue is that switching between modes takes a few seconds.

You used this hex?https://github.com/Safecast/bGeigieNanoKit/blob/master/.pio/build/fio/firmware.hex

**Comment by pawelngei** [comment]
@robouden correct! It might be that the previous one was flashed wrong too, not necessarily broken.

I just completed a walk with this one and the log seems to be correct.

**Comment by pawelngei** [comment]
I just submitted my first set of coordinates at https://api.safecast.org/en-US/bgeigie_imports/52867 ! Thank you all for the help!

For all the future visitors in this thread, what I learned:

- If the GPS doesn't lock in after half an hour, something is probably wrong.
- The bGeigie Surface Mode second line is not supposed to flicker. Check the time in the Logging mode, it might mean that it's off.
- Firmware 1.4.3 might potentially not work on some devices / I might have flashed it wrong.
- Upgrading to 1.4.4 helped me
- I upgraded from https://github.com/Safecast/bGeigieNanoKit/blob/master/.pio/build/fio/firmware.hex file with a command `avrdude -DV -p atmega328p -P /dev/ttyUSB0 -c arduino -b 57600 -U flash:w:firmware.hex:i` (please remember to download the raw HEX file, not the html with it).
- The bottom of the bent connectors used to program Arduino Fio should be cut so that they don't touch the motherboard
- The 3-5s lag when switching between Logging and Surface mode is normal
- If the GPS works but you can't see any radiation readings, check the iRover connection as per [this image](https://raw.githubusercontent.com/Safecast/bGeigieNanoKit/master/nano%20manual%20named%20pics/manual%20update%20Aug%202018%20small%20JPEG%20selects/016-TripleConnectorWithLead1000pxAnnotated.jpg).

I think with that, we can close the issue

**Comment by hinner** [comment]
Thank you for this summary!

All the best,

Kajetan

Am 03.08.21 um 23:13 schrieb Paweł Ngei:
