### ISSUE TITLE
Question: where can I buy bgeigie nano?

### ISSUE THREAD

**Issue by margre8** [Safecast/bGeigieNanoKit#70]
Dear Safecast developers,

I would like to buy the Safecast bgeigie nano kit but when I try to look at kithub shop I am constantly unable to connect with the server and it looks like the shop does not work. Is the shipping of the kit suspended or is there some other way?

Thank you for help

**Comment by robouden** [comment]
Dear Magre8,

- Are you in  a hurry to get one?
- We could offer a bGeigieZen that is already build by me, and working correctly for measurements and for creating bGeigieNano  compatible  log file. (still very beta), but much more modern and flexible to work with and off it at about the same price as bGeigieNano as mentioned on GitHub. You may need to update the firmware later to get the updates. But that should be very easy. Just a USC C cable and one file, More information at [](https://bgeigiezen.safecast.jp/). Website for bGeigieZen is also still in development.
- Let me know what you want to do.

Regards,
Rob Oudendijk

**Comment by margre8** [comment]
@robouden I appreciate your offer, but I am not currently hurry to get one because I have one device borrowed. May I contact you later if I would buy bGeigieZen?
I would like to ask you, am I understand that the bGeigieZen will replace the bGeigie nano and this is the reason why bGeigie nano is not for sale?

Thank you for your Willingness

**Comment by robouden** [comment]
You can contact me anytime.

The reason that the bGeigieNanokit is not available is that the parts are hard to get these days. And also Kithub stopped completely. Owner closed it.

Yes, bGeigieZen will replace the bGeigieNano.

Regards,
rob Oudendijk

**Comment by margre8** [comment]
Thank you for answer, if I would like to contact you regarding bGeigieZen should I use another GitHub issue, or via Safecast website?

**Comment by robouden** [comment]
You can contact me through any of my emails.

Regards,
Rob



Regards,
Rob Oudendijk Yuka Hayashi
https://yr-design.biz <http://yr-design.biz/>   https://oudendijk.biz
<http://oudendijk.biz/>  https://about.me/robouden
<http://about.me/robouden>
tel +81 80-22605966  Skype: robouden  Facebook:robouden
<http://on.fb.me/QeKw2P> linkedin:robouden
<https://www.linkedin.com/in/roboudendijk>
