### ISSUE TITLE
http://nano.safecast.org/ is down

### ISSUE THREAD

**Issue by abitrolly** [Safecast/bGeigieNanoKit#71]
Link http://nano.safecast.org/ that is written in repository description doesn't work anymore.

**Comment by robouden** [comment]
Thanks for noting it. Now it is fixed.

**Comment by abitrolly** [comment]
Still down for me. Maybe needs some time to update.

**Comment by robouden** [comment]
That site is not there anymore. A new link is in the description now.[Click here](https://safecast.org/devices/bgeigie-nano/)

**Comment by abitrolly** [comment]
Oh. I see now. Then it is fixed. )
